### ISSUE TITLE
Document what `^` does for group elements, link it in the index, and fix ^ index entries

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4052]
Several closely related issues regarding the `^` operator:

- for a beginner it is needlessly difficult to find out what `g^h` does when `g` and `h` are group elements. Sure, for group theory people it is usually "clear" that this must be h^{-1}*g*h`, but there are books and communities where it is different, so I think it'd be helpful to state this explicitly *somewhere* in the manual

- ideally that place also would have an index entry for `^` so that `?^` would find it

- in https://www.gap-system.org/Manuals/doc/ref/chapInd.html I see two entries for `^` but sorted into different positions; the same happens for other operators such as `\<`:
```
...
\XYZ 27.2 
^, for class functions 72.4 
\< 31.11-1 
    for associative words 37.3-2 
    for nonassociative words 36.2-2 
    for pcwords 46.2-1 
    for permutations 42.2-1 
    for two elements in a f.p. group 47.3-2 
    for two strings 27.6-2 
\* 31.12-1 
    for pcwords 46.2-2 
\*, for transformations 53.4 
...
\<, for transformations 53.4 
...
\= 31.11-1 
    for associative words 37.3-1 
    for nonassociative words 36.2-1 
    for pcwords 46.2-1 
    for permutations 42.2-1 
\=, for transformations 53.4 
\=, for two elements in a f.p. group 47.3-1 
    for two elements in a f.p. semigroup 52.3-1 
    for two strings 27.6-1 
...
\^ 31.12-1 
    for a field and a pair of integers 61.9-5 
    for a field and an integer 61.9-4 
\^, for a positive integer and a transformation 53.4 
    for a transformation and a permutation 53.4 
...
\{\} 21.3-1 
\{\}\:\= 21.4-1 
^ 4.13 
abelian number field 60.2-3 
...
```

**Comment by ThomasBreuer** [comment]
Yes, the meaning of "conjugation" is apparently not defined explicitly in the GAP manual (contrary to the meaning of "commutator").

If one asks for `?^` then one finds two exact matches in the GAP Reference Manual.

- The one for `^` belongs to the section about "Arithmetic Operators" in the "Language" chapter, and the paragraph about the operator `^` could be extended by the definition for the case of two group elements.
- The one for `\^` belongs to the section about "Arithmetic Operations for Elements" in the "Domains" chapter, and gives the advice to consult the index entries for `\^`; thus an index entry with the key "^ for two group elements" should be created.

If one asks for `?conjugation` then the best hit is the section about `OnPoints`, which has an index entry for that keyword. The text of this manual section says that conjugation is done by the operation `^` but does not say what conjugation is. Here would be another natural place for stating the definition of conjugation.
It would make sense to add an index entry with key "conjugation" to the place where the use of `\^` for conjugation is explained.

**Comment by fingolfin** [comment]
All of what you write indeed sounds quite reasonable.

I still wonder about the strange sorting; perhaps @frankluebeck has an idea what causes that?

**Comment by frankluebeck** [comment]
(1) I would say, that the documentation is ok. If I ask in GAP
```
?^
```
then the first hit explains the arithmetic operators. In particular, it says that if the second operand is a group element the operator means the operation on points. And 
```
?OnPoints
```
tells that if the first operator is also a group element then the operation means conjugation. 

Of course, it wouldn't hurt to mention this case of two groups elements more explicitly in the paragraph on arithmetic operators.

(2) Concerning the sorting in the index: I have no idea. In my GAP (master branch) I don't have the second line as shown above. For me it looks like:
```
  ^ 4.13 
      for class functions 72.4 
```

(the entries `\^` are also together and come a bit earlier).

**Comment by fieker** [comment]
On Tue, Jun 23, 2020 at 09:42:04AM -0700, frankluebeck wrote:
> (1) I would say, that the documentation is ok. If I ask in GAP
> ```
> ?^
> ```
> then the first hit explains the arithmetic operators. In particular, it says that if the second operand is a group element the operator means the operation on points. And 
> ```
> ?OnPoints
> ```
> tells that if the first operator is also a group element then the operation means conjugation. 
This was part of my original complaint/ question: what is "the"
definition of conjugation? This is missing. a^-1 b a or a b a^-1? I have
since figured it out, and Max explained it, but this is crucial to
non-group people.

**Comment by frankluebeck** [comment]
I have now seen that the sorting problem mentioned above concerns the HTML version of the manual (I first thought that the text version was meant). This is due to a missing `Key` attribute in some index entry (which caused that a string with markup was used for the sorting). This case and a few more similar ones should be fixed by the pull request "Fix some sort keys #4060".

**Comment by fingolfin** [comment]
PR #4060 indeed improves things a bit. But I can't say it's fixed. I still get this in the index:
```
^, for class functions 72.4 
\< 31.11-1 
    for associative words 37.3-2 
    for nonassociative words 36.2-2 
    for pcwords 46.2-1 
    for permutations 42.2-1 
    for two elements in a f.p. group 47.3-2 
    for two matrix objects 26.6-1 
    for two strings 27.6-2 
    for two vector objects 26.6-1 
\* 31.12-1 
    for Matrix object and scalar 26.10-2 
    for pcwords 46.2-2 
    for scalar and matrix object 26.10-2 
    for scalar and vector object 26.8-2 
\*, for transformations 53.4 
\*, for two matrix objects 26.10-2 
    for two vector objects 26.8-2 
    for vector object and scalar 26.8-2 
\+ 31.12-1 
    for two matrix objects 26.10-2 
    for two vector objects 26.8-2 
\-, for two matrix objects 26.10-2 
    for two vector objects 26.8-2 
\. 29.7-3 
\.\:\= 29.7-3 
\/ 31.12-1 
    for a free group and a list of elements 47.2-1 
    for a free group and a list of pairs of elements 47.2-1 
    for a free semigroup or monoid and a list of pairs of elements 52.2-1 
\/, for a transformation and a permutation 53.4 
\/, for matrix object and scalar 26.10-2 
    for vector object and scalar 26.8-2 
\<, for transformations 53.4 
\= 31.11-1 
    for associative words 37.3-1 
    for nonassociative words 36.2-1 
    for pcwords 46.2-1 
    for permutations 42.2-1 
\=, for transformations 53.4 
\=, for two elements in a f.p. group 47.3-1 
    for two elements in a f.p. semigroup 52.3-1 
    for two matrix objects 26.6-1 
    for two strings 27.6-1 
    for two vector objects 26.6-1 
\[\] 21.2-1 
    for a row list matrix 26.12-3 
    for a vector object and an integer 26.7-1 
\[\]\:\= 21.2-1 
    for a row list matrix and a vector object 26.12-4 
    for a vector object and an integer 26.7-1 
\^ 31.12-1 
    for a field and a pair of integers 61.9-5 
    for a field and an integer 61.9-4 
\^, for a positive integer and a transformation 53.4 
    for a transformation and a permutation 53.4 
\^, for matrix object and integer 26.10-2 
\in, element test for lists 21.8-1 
    for a collection 30.6-1 
    for strictly sorted lists 21.19-1 
\mod 31.12-1 
    for residue class rings 14.5-1 
    for two pcgs 45.9-5 
\{\} 21.3-1 
    for a row list matrix 26.12-5 
    for a vector object and a list 26.7-1 
\{\}\:\= 21.4-1 
    for row list matrices 26.12-6 
^ 4.13 
```

Note that `^` appears both at the start and at the end. (One might also wonder whether we really should have index entries for `^` and whether those shouldn't all be `\^`, but that's another matter).

You can also see that `\<` still appears in two different (non-adjacent) places. And finally, I find the grouping weird: E.g. why are the entries for `\*` subkeys not all grouped under a single `\*` key heading? That is, why do we see this:
```
\* 31.12-1 
    for Matrix object and scalar 26.10-2 
    for pcwords 46.2-2 
    for scalar and matrix object 26.10-2 
    for scalar and vector object 26.8-2 
\*, for transformations 53.4 
\*, for two matrix objects 26.10-2 
    for two vector objects 26.8-2 
    for vector object and scalar 26.8-2 
```
instead of this:
```
\* 31.12-1 
    for Matrix object and scalar 26.10-2 
    for pcwords 46.2-2 
    for scalar and matrix object 26.10-2 
    for scalar and vector object 26.8-2 
    for transformations 53.4 
    for two matrix objects 26.10-2 
    for two vector objects 26.8-2 
    for vector object and scalar 26.8-2 
```

One guess: keys that are in a subsection (such as 53.4) are not subsumed, hence " for transformations 53.4" appears on its own. That seems strange, though?

**Comment by fingolfin** [comment]
UPDATE: my previous comment was partially wrong (based on wrong index output), so I just corrected it. Sorry for any resulting confusion.

**Comment by fingolfin** [comment]
I guess we can fix (resp. work around) the issue with the "for transformations" by editing the corresponding part of the documentation to use `ManSection` instead.

And the remaining `\<` issue is because of the use of `&lt;` in `doc/ref/trans.xml`
```XML
    <Mark><C><A>f</A> &lt; <A>g</A></C></Mark>
    <Item>
      <Index Key="\&lt;" Subkey="for transformations"><C>\&lt;</C></Index>
```

**Comment by frankluebeck** [comment]
The display of the `\*` entries cited above is correct. The entry from 53.4 is a string formatted as code  (&lt;C>\\*&lt;/C>) while the others have markup as function names (depending on the used CSS they could be displayed differently, so we need to print the different versions). Of course, it is better to use `ManSection`s in 53.4 instead of index entries, as done in  #4063. Then, as a side effect, all these entries become the same.

The case of '\\&lt;' in different places is actually a GAPDoc bug. The special characters `&lt;`,  `&gt;` and `&amp;` where accidentally HTML-escaped in the sort key (for the HTML versions of  manuals).

Similarly, in GAPDoc the characters `\\` and `_` where accidentally escaped in the sort key of `\\index{}` entries for the LaTeX version of manuals.

The problems in GAPDoc should be fixed in [this commit](https://github.com/frankluebeck/GAPDoc/commit/10d5a00bc6bf9a856df1907224e0c3bfde0586ee).

**Comment by jackschmidt** [comment]
Am I right in thinking that the "good-first-issue" part of this issue has been handled already in #4059 ?

I still see some small amount of split in the html manual (`\^` versus `^`) for example, but it was easy to find the new entries from within GAP and on the html page.

**Comment by fingolfin** [comment]
There is still the "split" to resolve, but otherwise this is indeed resolved.

**Comment by fingolfin** [comment]
I tried to resolve this, but I could not figure out how to adjust e.g. `<Index Key="^">` to instead insert `\^` as key in a way that makes it appear right in the index. I tried `"\^"` and `"\\^"` but both result in different kinds of nonsense in the HTML resp. PDF index (with latest GAP master and GAPDoc 1.6.4). Perhaps @frankluebeck knows how to do it?

**Comment by frankluebeck** [comment]
I don't understand what you mean by _"split" to resolve_. There is now a block for `\^` and one for `^` in their alphabetic posiions. This looks correct to me. 

Do you want to sort the `^` entries together with the `\^` ones? If you use the same key for them then the sorting within that
block will be according to the subkey. And so the different entries need to be printed several times (maybe not what you want?):
```
^ 4.13
\^ 31.12-1
    for a field and a pair of integers 61.9-5
    for a field and an integer 61.9-4
    for a partial permutation and a permutation or partial permutation 54.5-4
    for a positive integer and a partial permutation 54.5-2
    for a positive integer and a transformation 53.4-1
    for a transformation and a permutation 53.4-2
^, for class functions 72.4
\^, for matrix object and integer 26.10-2
^, for two group elements 4.13
```
If you want to keep the three entries for `^` together you must use a different key, say `Key="\^Z"` to get:
```
\^ 31.12-1 
    for a field and a pair of integers 61.9-5
    for a field and an integer 61.9-4
    for a partial permutation and a permutation or partial permutation 54.5-4
    for a positive integer and a partial permutation 54.5-2
    for a positive integer and a transformation 53.4-1
    for a transformation and a permutation 53.4-2
    for matrix object and integer 26.10-2
^ 4.13
    for class functions 72.4
    for two group elements 4.13
```
But this hack must then be applied to any further entry for `^` that might be introduced later. I would not do this and leave the `^` where it is now

(The alphabetic sorting of LaTeX/makeindex seems to be a bit different here, let us just accept this.)

**Comment by fingolfin** [comment]
From my POV this is resolved. Thanks everyone!
